#lang sicp

(#%require "3.25.rkt")
(#%require rackunit)

(define t (make-table 'table))
(check-false (assoc t '(0)))
(check-false (lookup t '(0)))
(insert t '(0) 'a)
(check-eq? (lookup t '(0)) 'a)
(insert t '(0 0) 'b)
(check-eq? (lookup t '(0)) 'a)
(check-eq? (lookup t '(0 0)) 'b)
(insert t '(0 0 0) 'c)
(check-eq? (lookup t '(0)) 'a)
(check-eq? (lookup t '(0 0)) 'b)
(check-eq? (lookup t '(0 0 0)) 'c)
(insert t '(0 1) 'd)
(check-eq? (lookup t '(0)) 'a)
(check-eq? (lookup t '(0 0)) 'b)
(check-eq? (lookup t '(0 0 0)) 'c)
(check-eq? (lookup t '(0 1)) 'd)
(insert t '(0) 'e)
(check-eq? (lookup t '(0)) 'e)
(insert t '(1) 'f)
(insert t '(1 1 1) 'g)
(check-eq? (lookup t '(1)) 'f)
(check-eq? (lookup t '(1 1 1)) 'g)
(insert t '(2 2 2 2) 'h)
(check-eq? (lookup t '(2 2 2 2)) 'h)
(insert t '(2) 'i)
(insert t '(2 3) 'j)
(check-eq? (lookup t '(2)) 'i)
(check-eq? (lookup t '(2 3)) 'j)